development:
  adapter: postgresql
  encoding: unicode
  database: bandwag_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bandwag_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: bandwag_production
  pool: 5
  username: postgres
  password:
